// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as template$0 from "../template/models.js";

/**
 * AppSettings 全局应用设置（JSON 字段名与 Python 版 settings.json 逐字一致，保证老用户零迁移）。
 */
export interface AppSettings {
    "builtin_columns"?: template$0.BuiltinColumn[] | null;
    "phone_validate": boolean;
    "phone_highlight": boolean;
    "phone_merge": boolean;
    "phone_separators": string[] | null;
    "csv_encoding": string;
    "csv_separator": string;
    "txt_encoding": string;
    "txt_separator": string;
    "vcf_fields": string[] | null;
    "vcf_name_prefix": string;
    "vcf_name_suffix": string;
    "vcf_timestamp": boolean;
    "vcf_timestamp_position": string;
    "vcf_show_import_guide": boolean;
    "declaration_detect": boolean;
    "declaration_keywords": string[] | null;
    "source_separator": string;
    "source_encoding": string;
    "log_debug": boolean;
    "log_retain_days": number;
    "log_auto_clean": boolean;
    "auto_update_enabled": boolean;
    "use_system_proxy": boolean;
    "update_url": string;
    "download_dir": string;
    "install_dir": string;
}
