// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Applied 模板应用到数据源后的完整映射结果。
 */
export interface Applied {
    "name": string;
    "matches": ColumnMatch[] | null;

    /**
     * 模板列 key → 源列名
     */
    "mapping": { [_ in string]?: string } | null;
    "missing_cols": string[] | null;
}

/**
 * BuiltinColumn 内置列（语义字段），可增删改查。
 */
export interface BuiltinColumn {
    /**
     * 语义键（创建时分配，不再修改）
     */
    "key": string;

    /**
     * 显示名（用户可改）
     */
    "label": string;

    /**
     * 匹配别名（用户可维护）
     */
    "aliases": string[] | null;

    /**
     * vCard 属性名（如 NOTE/EMAIL）；空则自定义字段默认 NOTE
     */
    "vcf_prop"?: string;
}

/**
 * ColumnMatch 单个模板列的匹配结果。
 */
export interface ColumnMatch {
    "template_col": TemplateColumn;

    /**
     * 匹配到的源表列名；未匹配为 nil
     */
    "source_col": string | null;

    /**
     * "manual" | "exact" | "alias" | "none"
     */
    "status": string;
}

/**
 * Suggestion 单个模板的匹配建议（按 Matched 降序排列）。
 */
export interface Suggestion {
    "name": string;

    /**
     * 匹配到的模板列数
     */
    "matched": number;

    /**
     * 模板列总数
     */
    "total": number;

    /**
     * 未匹配的模板列名
     */
    "missing_cols": string[] | null;
}

/**
 * Template 一个模板 = 名称 + 列集合 + 可选建议映射（key → 源列名，应用时优先恢复）。
 */
export interface Template {
    "name": string;
    "columns": TemplateColumn[] | null;
    "mappings": { [_ in string]?: string } | null;

    /**
     * "excel"/"text"；None=不限
     */
    "source_format"?: string | null;
}

/**
 * TemplateColumn 模板中的一列。
 */
export interface TemplateColumn {
    /**
     * 语义键（稳定标识：name/phone/company/website/custom_<n>）
     */
    "key": string;

    /**
     * 列显示名（导出表头）
     */
    "name": string;

    /**
     * 导出时是否包含
     */
    "enabled": boolean;
}
