// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportRow 单条导出数据行（一个手机号占一行；无手机映射时一源行一行）。
 */
export interface ExportRow {
    /**
     * 与模板 enabled 列一一对应的值列表
     */
    "values": string[] | null;

    /**
     * 该行手机号是否通过校验（未启用校验或空号恒为 true）
     */
    "phone_valid": boolean;

    /**
     * 对应源表数据行号，从 1 开始计数，表头行不计
     */
    "source_row_index": number;

    /**
     * 同一源行拆分出的行数（1=无拆分）
     */
    "merge_span": number;

    /**
     * 拆分组首行（姓名合并起始行）
     */
    "is_first_of_split": boolean;
}

/**
 * PreviewData 数据转换的完整预览结果。
 */
export interface PreviewData {
    "rows": ExportRow[] | null;
    "invalid_count": number;
    "invalid_summary": string[] | null;
}
