// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SheetData 从单个 Sheet 读取的全部数据。
 */
export interface SheetData {
    "sheet_name": string;
    "headers": string[] | null;
    "rows": ({ [_ in string]?: string } | null)[] | null;

    /**
     * 是否跳过了首行声明（企查查导出）
     */
    "declaration_skipped": boolean;
}

/**
 * SheetSummary 单个 Sheet 的名称与数据行数（下拉选择时展示）。
 */
export interface SheetSummary {
    "name": string;
    "rows": number;
}
