// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Item 一个卸载清理项（前端展示用，不含路径）。
 */
export interface Item {
    /**
     * 稳定标识（app / data / logs / downloads）
     */
    "key": string;

    /**
     * 勾选文案
     */
    "label": string;

    /**
     * 高风险项：默认不勾选 + 确认框标注（防误删用户数据）
     */
    "risky": boolean;

    /**
     * 默认勾选状态
     */
    "default_checked": boolean;

    /**
     * 目标是否存在（false = 无残留）
     */
    "exists": boolean;
}

/**
 * Result 单项执行结果（Error 为空 = 成功或本就无残留）。
 */
export interface Result {
    "key": string;
    "error"?: string;
}
