// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App Wails 服务：依赖通过字段注入（不读全局变量）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as excel$0 from "../excel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as template$0 from "../template/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uninstall$0 from "../uninstall/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyTemplate 将指定模板应用到源表头（覆盖语义：按模板 mappings + 自动匹配重建映射）。
 */
export function ApplyTemplate(headers: string[] | null, name: string): $CancellablePromise<template$0.Applied | null> {
    return $Call.ByID(525582212, headers, name);
}

/**
 * CheckUpdate 检查最新版本（复用 internal/updater，更新源取设置 update_url）。
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(1115479699);
}

/**
 * DetectTruncatedNumbers 检测 Sheet 中疑似号码/身份证截断补零的列提示（读表后弹窗用）。
 */
export function DetectTruncatedNumbers(data: excel$0.SheetData | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(3636275837, data);
}

/**
 * DownloadProgress 返回当前下载进度（前端轮询）。
 */
export function DownloadProgress(): $CancellablePromise<$models.DownloadProgress> {
    return $Call.ByID(3235049317);
}

/**
 * ExportLogs 将最新的日志文件复制到 dest（设置页「日志」tab 导出按钮）。
 * 返回实际写入的目标路径；日志目录为空时返回错误。
 */
export function ExportLogs(dest: string): $CancellablePromise<string> {
    return $Call.ByID(1763863467, dest);
}

/**
 * ExportWithColumns 用会话列集合导出（不读磁盘模板）。
 */
export function ExportWithColumns(data: excel$0.SheetData | null, columns: template$0.TemplateColumn[] | null, manualMap: { [_ in string]?: string } | null, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(576468635, data, columns, manualMap, outputPath);
}

/**
 * ExportWithTemplate 用指定模板 + 手动映射导出（Spec 步骤 8-10）。
 */
export function ExportWithTemplate(data: excel$0.SheetData | null, templateName: string, manualMap: { [_ in string]?: string } | null, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(3539023594, data, templateName, manualMap, outputPath);
}

/**
 * LicenseActivate 激活码激活（契约 §7 完整流程：验签 → 类型/过期检查 → 在线激活/hybrid 放行）。
 */
export function LicenseActivate(key: string): $CancellablePromise<$models.LicenseActivateResult | null> {
    return $Call.ByID(1239550528, key);
}

/**
 * LicenseDeactivate 解绑当前设备（在线解绑成功才清除本地，契约 §5）。
 */
export function LicenseDeactivate(): $CancellablePromise<void> {
    return $Call.ByID(3207092579);
}

/**
 * LicenseStatus 返回当前激活状态。
 */
export function LicenseStatus(): $CancellablePromise<$models.LicenseStatusView | null> {
    return $Call.ByID(3130449983);
}

/**
 * ListSheets 列出文件的所有 Sheet（下拉选择用）。
 * xls 源文件先转换为 xlsx 再处理（统一处理管线，决策见 docs/migration/08-status-report.md）。
 */
export function ListSheets(path: string): $CancellablePromise<excel$0.SheetSummary[] | null> {
    return $Call.ByID(1481239526, path);
}

/**
 * OpenPath 用系统文件管理器打开目录，或定位并选中文件（对齐 update_sop：open -R / explorer /select）。
 */
export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(179410065, path);
}

/**
 * PreviewSummary 返回预览区顶部汇总文案（vcf 前缀说明 + 异常手机号计数）。
 */
export function PreviewSummary(total: number, format: string, invalidCount: number): $CancellablePromise<string> {
    return $Call.ByID(3906714658, total, format, invalidCount);
}

/**
 * PreviewText 返回与导出文件内容一致的文本预览（vcf/csv/txt 所见即所得，最多前 rowLimit 行数据）。
 * xlsx 表格预览请用 PreviewWithMapping 的结构化结果。
 */
export function PreviewText(data: excel$0.SheetData | null, templateName: string, manualMap: { [_ in string]?: string } | null, format: string, rowLimit: number): $CancellablePromise<string> {
    return $Call.ByID(492660149, data, templateName, manualMap, format, rowLimit);
}

/**
 * PreviewTextWithColumns 用会话列集合生成文本预览。
 */
export function PreviewTextWithColumns(data: excel$0.SheetData | null, columns: template$0.TemplateColumn[] | null, manualMap: { [_ in string]?: string } | null, format: string, rowLimit: number): $CancellablePromise<string> {
    return $Call.ByID(1424883760, data, columns, manualMap, format, rowLimit);
}

/**
 * PreviewWithColumns 用会话列集合构建预览（不读磁盘模板）。
 */
export function PreviewWithColumns(data: excel$0.SheetData | null, columns: template$0.TemplateColumn[] | null, manualMap: { [_ in string]?: string } | null): $CancellablePromise<core$0.PreviewData | null> {
    return $Call.ByID(2782807065, data, columns, manualMap);
}

/**
 * PreviewWithMapping 用指定模板 + 手动映射构建预览（SPEC 步骤 5-7）。
 * templateName 为空时用内置默认模板；manualMap = {模板列 key: 源列名}。
 */
export function PreviewWithMapping(data: excel$0.SheetData | null, templateName: string, manualMap: { [_ in string]?: string } | null): $CancellablePromise<core$0.PreviewData | null> {
    return $Call.ByID(4037029028, data, templateName, manualMap);
}

/**
 * ReadLogs 读取日志目录中最近的日志内容（设置页「日志」tab）。
 * limit 为每条日志的最大行数；按修改时间取最新的日志文件。
 */
export function ReadLogs(limit: number): $CancellablePromise<string[] | null> {
    return $Call.ByID(1318339985, limit);
}

/**
 * ReadSheet 读取指定 Sheet（前端预览用，返回前 200 行避免大表卡顿）。
 * xls 源文件先转换为 xlsx 再读取。
 */
export function ReadSheet(path: string, sheetName: string, skipDeclaration: boolean): $CancellablePromise<excel$0.SheetData | null> {
    return $Call.ByID(406636397, path, sheetName, skipDeclaration);
}

/**
 * SessionMatch 用会话内列集合匹配（不读磁盘模板；列编辑后重匹配用）。
 */
export function SessionMatch(headers: string[] | null, columns: template$0.TemplateColumn[] | null, manualMap: { [_ in string]?: string } | null): $CancellablePromise<template$0.ColumnMatch[] | null> {
    return $Call.ByID(3885401991, headers, columns, manualMap);
}

/**
 * SettingsGet 返回当前全局设置（设置页展示用）。
 */
export function SettingsGet(): $CancellablePromise<settings$0.AppSettings | null> {
    return $Call.ByID(2731786025);
}

/**
 * SettingsReset 恢复默认设置并持久化（设置页「恢复默认设置」）。
 */
export function SettingsReset(): $CancellablePromise<void> {
    return $Call.ByID(562018686);
}

/**
 * SettingsUpdate 合并更新全局设置（前端传变更字段，缺失字段保持原值）并持久化。
 * 支持字段（JSON key 与 settings.json 逐字一致）：
 * 
 * 	phone_validate / phone_highlight / phone_merge / phone_separators /
 * 	csv_encoding / txt_encoding / txt_separator / vcf_fields /
 * 	vcf_name_prefix / vcf_name_suffix / vcf_timestamp / vcf_timestamp_position /
 * 	vcf_show_import_guide / declaration_detect / declaration_keywords
 */
export function SettingsUpdate(partial: { [_ in string]?: any } | null): $CancellablePromise<void> {
    return $Call.ByID(3734531934, partial);
}

/**
 * StartDownloadUpdate 启动后台更新包下载（进行中时拒绝重复启动）。
 */
export function StartDownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1795604571);
}

/**
 * SuggestTemplates 对全部已存模板打分，返回 Matched>0 的建议列表（读入数据源后提示可用模板）。
 */
export function SuggestTemplates(headers: string[] | null): $CancellablePromise<template$0.Suggestion[] | null> {
    return $Call.ByID(3878471067, headers);
}

/**
 * TemplateCreate 新建模板（列 = key/name 列表；key 为空时按 custom_<n> 生成）。
 */
export function TemplateCreate(name: string, columns: template$0.TemplateColumn[] | null): $CancellablePromise<void> {
    return $Call.ByID(1932930040, name, columns);
}

/**
 * TemplateCreateFromHeaders 从源表头一键生成模板（SPEC 步骤 4 快捷入口）。
 * 列 key：命中内置列别名/列名 → 用内置 key；否则 custom_<n>。
 * 同时写入 mappings（key→源列名），下次 Apply 可直接恢复。
 */
export function TemplateCreateFromHeaders(name: string, headers: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3882102266, name, headers);
}

/**
 * TemplateDelete 删除模板。
 */
export function TemplateDelete(name: string): $CancellablePromise<void> {
    return $Call.ByID(2954945447, name);
}

/**
 * TemplateList 返回全部模板（按名称排序）。
 */
export function TemplateList(): $CancellablePromise<(template$0.Template | null)[] | null> {
    return $Call.ByID(1979165684);
}

/**
 * TemplateMatches 返回模板列与源表列的自动匹配结果（SPEC 步骤 5：exact/alias/none 状态）。
 * manualMap 为已手动调整的映射（key → 源列名），用于增量更新。
 */
export function TemplateMatches(headers: string[] | null, templateName: string, manualMap: { [_ in string]?: string } | null): $CancellablePromise<template$0.ColumnMatch[] | null> {
    return $Call.ByID(4075270393, headers, templateName, manualMap);
}

/**
 * TemplateRename 重命名模板（文件随模板名）。
 */
export function TemplateRename(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2957611694, oldName, newName);
}

/**
 * TemplateSetMappings 更新已有模板的建议映射（导出后持久化，下次 Apply 优先恢复）。
 */
export function TemplateSetMappings(name: string, mappings: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(159628771, name, mappings);
}

/**
 * TemplateUpdate 更新已有模板的列集合（列映射页增删改后持久化）。
 */
export function TemplateUpdate(name: string, columns: template$0.TemplateColumn[] | null): $CancellablePromise<void> {
    return $Call.ByID(3655496877, name, columns);
}

/**
 * UninstallItems 返回当前平台的卸载清理项（含存在性检测，前端勾选展示用）。
 */
export function UninstallItems(): $CancellablePromise<uninstall$0.Item[] | null> {
    return $Call.ByID(3367838144);
}

/**
 * UninstallRemove 按 key 逐项执行清理；单项失败不中断后续项，结果写入日志。
 */
export function UninstallRemove(keys: string[] | null): $CancellablePromise<uninstall$0.Result[] | null> {
    return $Call.ByID(690342476, keys);
}

/**
 * Version 返回应用版本号（关于页展示 + 更新比较基准）。
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(3217321430);
}
