// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress 下载进度状态（前端轮询展示）。
 */
export interface DownloadProgress {
    /**
     * idle / downloading / done / error
     */
    "status": string;

    /**
     * 0-100（总大小未知时为 0）
     */
    "percent": number;

    /**
     * 已下载字节
     */
    "done": number;

    /**
     * 总字节（未知为 0）
     */
    "total": number;
    "file_path"?: string;

    /**
     * 安装替换指引文案
     */
    "guide"?: string;
    "error"?: string;
}

/**
 * LicenseActivateResult 激活操作结果（前端展示用）。
 */
export interface LicenseActivateResult {
    "ok": boolean;

    /**
     * 失败错误码（契约 §8 速查表）
     */
    "code": string;

    /**
     * hybrid 放行（网络不可用，待在线确认）
     */
    "pending_online": boolean;

    /**
     * 到期时间（平台或本地）
     */
    "expires_at": number;

    /**
     * 用户可读提示
     */
    "message": string;
}

/**
 * LicenseStatusView 激活状态展示（前端激活页用）。
 */
export interface LicenseStatusView {
    "is_pro": boolean;

    /**
     * 授权类型（"" = 未激活）
     */
    "type": string;

    /**
     * 到期时间戳（ms；0 = 未激活）
     */
    "expires_at": number;

    /**
     * 激活时间戳（ms；0 = 未激活）
     */
    "activated_at": number;
}

/**
 * UpdateInfo 更新检查结果（前端「更新」tab 展示）。
 */
export interface UpdateInfo {
    "current": string;
    "latest": string;
    "has_update": boolean;

    /**
     * 更新包下载地址
     */
    "zip_url"?: string | null;

    /**
     * 更新包字节数
     */
    "zip_size"?: number | null;

    /**
     * 更新说明
     */
    "notes"?: string;
    "error"?: string;
}
